package com.example.fragmennba;

import java.util.ArrayList;

public class NbaData {
    private static String[] title = new String[]{"Atlanta Hawks", "Boston Celtics",
            "Brooklyn Nets", "Charlotte BobCats", "Chicago Bulls", "Cleveland Cavaliers", "Dallas Mavericks",
            "Denver Nuggets", "Detroit Pistons", "Golden State Warriors", "Houston Rockets", "Indiana Pacers",
            "Los Angeles Clippers", "Los Angeles Lakers", "Memphis Grizzlies", "Miami Heat","Milwaukee Bucks",
            "Minnesota Timberwolves","New Orleans Hornets","New York Knickerbockers","Oklahoma City Thunder",
            "Orlando Magic","Philadelphia 76ers","Phoenix Suns","Portland Trail Blazers","Sacramento Kings",
            "San Antonio Spurs","Toronto Raptors","Utah Jazz","Washington Wizards"
    };

    private static String[] detail = new String[]{
            "The Atlanta Hawks are an American professional basketball team based in Atlanta, Georgia. They are part of the Southeast Division of the Eastern Conference in the National Basketball Association. They play their home games at Philips Arena in downtown Atlanta.\n",
            "The Boston Celtics are a National Basketball Association team based in Boston, Massachusetts. They play in the Atlantic Division of the Eastern Conference. Founded in 1946, the team is currently owned by Boston Basketball Partners LLC. The Celtics play their home games at the TD Garden, which they share with the Boston Bruins of the NHL. The Celtics’ 17 NBA Championships are the most for any NBA franchise.\n",
            "The Brooklyn Nets are a professional basketball team based in the New York City borough of Brooklyn. They are members of the Atlantic Division of the Eastern Conference in the National Basketball Association. The team is one of two NBA franchises that play home games in New York City; the other is the Knicks.\n",
            "The Charlotte Bobcats are a professional basketball team based in Charlotte, North Carolina. They play American basketball in the Southeast Division of the Eastern Conference in the National Basketball Association. The Bobcats were established in 2004 as an expansion team, two seasons after Charlotte’s previous NBA team, the Charlotte Hornets, relocated to New Orleans. The team is owned by former NBA player Michael Jordan, who acquired the team in 2010. The Bobcats play their home games at Time Warner Cable Arena in outer city Charlotte. As of the end of the 2011–12 season, the Bobcats have compiled a record of 229–411. In their 9-year history they have qualified for the postseason just once, which was during the 2009–10 season when they achieved a personal-best record of 44–38.\n",
            "The Chicago Bulls are a professional basketball team based in Chicago, Illinois, playing in the Central Division of the Eastern Conference in the National Basketball Association. They play their home games at the United Center. The Chicago Bulls were founded in 1966 and are well known for having one of the greatest dynasties in NBA and sports history during the 1990s, winning six championships in eight years with two three-peats. All six championship teams were led by Michael Jordan, Scottie Pippen and coach Phil Jackson. The first three championship teams included the likes of Bill Cartwright, Horace Grant, John Paxson and B.J. Armstrong, while the latter three had Luc Longley, Steve Kerr, Ron Harper, Toni Kukoč, and Dennis Rodman on the roster.\n",
            "The Cleveland Cavaliers are an American professional basketball team based in Cleveland, Ohio. They began playing in the National Basketball Association in 1970 as an expansion team. They play their home games at Quicken Loans Arena.\n",
            "The Dallas Mavericks are a professional basketball team based in Dallas, Texas. They are members of the Southwest Division of the Western Conference of the National Basketball Association. According to a 2012 Forbes Magazine report, they are the fourth-most valuable basketball franchise in the United States, valued at approximately $497 million; the franchise is surpassed in value only by the New York Knicks, the Los Angeles Lakers and the Chicago Bulls.\n",
            "The Denver Nuggets are a professional basketball team based in Denver, Colorado that plays in the National Basketball Association. The team was founded as the Denver Larks in 1967 as a charter franchise of the American Basketball Association but changed its name to Rockets before the first season. It changed its name again to the Nuggets in anticipation of a ABA-NBA merger in 1974, and played for the final ABA Championship title in 1976, losing to the New York Nets. The team joined the NBA in 1976 after the ABA-NBA merger and have some periods of success, making the playoffs for nine consecutive seasons in the 1980s and doing the same for the previous nine seasons. However, it has not made an appearance in a championship round since its last year in the ABA.\n",
            "The Detroit Pistons are a franchise of the National Basketball Association based in Auburn Hills, Michigan in Metro Detroit. In 1941, the team was founded in Fort Wayne, Indiana as the Fort Wayne Pistons, a member of the National Basketball League. The Pistons won two NBL championships before joining the NBA in 1948. Since moving to Detroit in 1957, the Pistons have won NBA championships in 1989, 1990 and 2004. The team’s home arena is The Palace of Auburn Hills.\n",
            "The Golden State  Warriors are an American professional basketball team based in Oakland, California. They are part of the Pacific Division of the Western Conference in the National Basketball Association. The team was first established in 1946, as the Philadelphia Warriors, in Philadelphia, Pennsylvania, where the franchise won the championship in the inaugural season of the Basketball Association of America, the league that would eventually become the National Basketball Association after a merger with the National Basketball League.\n",
            "The Houston Rockets are an American professional basketball team based in Houston, Texas. The team plays in the Southwest Division of the Western Conference in the National Basketball Association. The team was established in 1967, and played in San Diego, California for four years, before being moved to Houston.\n",
            "The Indiana Pacers are a professional basketball team based in Indianapolis, Indiana. They are members of the Central Division in the Eastern Conference of the National Basketball Association. The Pacers play their home games at Bankers Life Fieldhouse, which they share with their WNBA counterpart, the Indiana Fever, also owned by Herb Simon.\n",
            "The Los Angeles Clippers are a professional basketball team in Los Angeles, California, United States. They play in the Pacific Division of the National Basketball Association. The club’s home games are played at Staples Center, an arena shared with the Los Angeles Lakers of the NBA, the Los Angeles Sparks of the Women’s National Basketball Association, and the Los Angeles Kings of the National Hockey League. The Los Angeles Clippers are the only NBA team based in California to not have won a Championship.\n",
            "The Los Angeles Lakers are an American professional basketball team based in Los Angeles, California. They play in the Pacific Division of the Western Conference in the National Basketball Association. The Lakers play their home games at Staples Center, which they share with their local NBA rival, the Los Angeles Clippers, the Los Angeles Kings of the NHL, and the Los Angeles Sparks of the WNBA. The Lakers are one of the most successful teams in the history of the NBA, and have won 16 championships, their last being in 2010. As of 2012, the Lakers are the most valuable NBA franchise according to Forbes, having an estimated value of $900 million.\n",
            "The Memphis Grizzlies are a professional basketball team based in Memphis, Tennessee, USA. The team is part of the Southwest Division of the Western Conference in the National Basketball Association. The Grizzlies play their home games at FedExForum. The team’s majority owner is Robert Pera.\n",
            "The Miami Heat are a professional basketball team based in Miami, Florida, United States. The team is a member of the Southeast Division in the Eastern Conference of the National Basketball Association. They play their home games at American Airlines Arena in Downtown Miami. The team owner is Micky Arison, the general manager is Pat Riley and the head coach is Erik Spoelstra. The mascot of the team is Burnie, an anthropomorphic fireball.\n",
            "The Milwaukee Bucks are a professional basketball team based in Milwaukee, Wisconsin, United States. They are part of the Central Division of the Eastern Conference in the National Basketball Association. The team was founded in 1968 as an expansion team, and currently plays at the BMO Harris Bradley Center. U.S. Senator Herb Kohl is the owner of the team, with Scott Skiles as head coach and John Hammond as general manager. The Bucks have won one league title, two conference titles, and thirteen division titles. They have featured such notable players as Kareem Abdul-Jabbar, Oscar Robertson, Bob Lanier, Ray Allen, Andrew Bogut, Michael Redd and Jon McGlocklin.\n",
            "The Minnesota Timberwolves are an American professional basketball team based in Minneapolis, Minnesota. They play in the Northwest Division of the Western Conference in the National Basketball Association. Founded in 1989, the team is currently owned by Glen Taylor. The Timberwolves played their home games in the Metrodome during their inaugural season, before moving to Target Center in 1990.\n",
            "The New Orleans Hornets are a professional basketball team based in New Orleans, Louisiana. They play in the Southwest Division of the Western Conference of the National Basketball Association. The franchise began play during the 1988–89 NBA season as the Charlotte Hornets, based in Charlotte, North Carolina, where they were located for fourteen seasons. Following the 2001–02 season, the team relocated to New Orleans, becoming the New Orleans Hornets. After three seasons in New Orleans, Hurricane Katrina forced the franchise to temporarily relocate to Oklahoma City, where they spent two seasons officially known as the New Orleans/Oklahoma City Hornets. The Hornets returned to New Orleans full-time for the 2007–08 season. The team will reportedly change its name to the New Orleans Pelicans for the 2013-14 NBA season.\n",
            "The New York Knickerbockers, referred to as the Knicks, are a professional basketball team based in New York City, New York. They are part of the Atlantic Division of the Eastern Conference in the National Basketball Association. The team was established in 1946 as one of the founding members of the Basketball Association of America, which became the NBA after merging with their rival, the National Basketball League in 1949.\n",
            "The Oklahoma City Thunder are a professional basketball franchise based in Oklahoma City, Oklahoma. They play in the Northwest Division of the Western Conference in the National Basketball Association; their home court is at Chesapeake Energy Arena. The Thunder’s NBA Development League affiliate is the Tulsa 66ers, who are owned by the Thunder. The Thunder are the only team in the Major professional North American sports leagues located in the state of Oklahoma.\n",
            "The Orlando Magic are an American professional basketball team based in Orlando, Florida. They are part of the Southeast Division of the Eastern Conference in the National Basketball Association (NBA). The franchise was established in 1989 as an expansion franchise, and has had such notable NBA stars such as Shaquille O’Neal, Penny Hardaway, Grant Hill, Tracy McGrady, Steve Francis, Dwight Howard, Vince Carter, and Rashard Lewis throughout its young history. The franchise has also been in the playoffs for more than half of their existence (14 playoff appearances in 23 years). Orlando has been the most successful of the four expansion teams brought into the league in 1988 and 1989 in terms of winning percentage. As of 2012, they are the only team in the “big four” sports leagues to play in the city of Orlando.\n",
            "The Philadelphia 76ers are a professional basketball team based in Philadelphia, Pennsylvania. They play in the Atlantic Division of the Eastern Conference of the National Basketball Association. Originally known as the Syracuse Nationals, they are one of the oldest franchises in the NBA. After their move to Philadelphia, a contest was held to decide on their new name. The winning name, chosen by Walter Stalberg, was the “76ers”, as a “tribute to the gallant men who forged this country’s independence” in 1776.\n",
            "The Phoenix Suns are a professional basketball team based in Phoenix, Arizona. They are members of the Pacific Division of the Western Conference in the National Basketball Association and the only team in their division not to be based in California. Their home arena since 1992 has been the US Airways Center, which was formerly known as America West Arena, in downtown Phoenix. The Arena is often referred to as the “Purple Palace” due to its purple seats.\n",
            "The Portland Trail Blazers, commonly known as the Blazers, are an American professional basketball team based in Portland, Oregon. They play in the Northwest Division of the Western Conference in the National Basketball Association. The Trail Blazers originally played their home games in the Memorial Coliseum, before moving to the Rose Garden in 1995. The franchise entered the league in 1970, and Portland has been its only home city. The franchise has enjoyed a strong following; from 1977 through 1995, the team sold out 814 consecutive home games, the longest such streak in American major professional sports. The Trail Blazers are also currently the only NBA team based in the binational Pacific Northwest, after the Vancouver Grizzlies relocated to Memphis and became the Memphis Grizzlies in 2001, and the Seattle SuperSonics relocated to Oklahoma City and became the Oklahoma City Thunder in 2008.\n",
            "The Sacramento Kings are a professional basketball team based in Sacramento, California, United States. They are members of the Pacific Division of the Western Conference in the National Basketball Association. The Kings are the only team in the Major professional North American sports leagues located in Sacramento; they play their home games at Sleep Train Arena.\n",
            "The San Antonio Spurs are an American professional basketball team based in San Antonio, Texas. They are part of the Southwest Division of the Western Conference in the National Basketball Association.The Spurs are one of four former American Basketball Association teams to remain intact in the NBA after the 1976 ABA-NBA merger and is the only former ABA team to have won an NBA championship. The Spurs’ four NBA championships are the fourth most in NBA history, behind only the Boston Celtics, Los Angeles Lakers and Chicago Bulls. The Spurs’ perfect record in NBA Finals series is surpassed only by the Chicago Bulls, who have won six without a loss; the Bulls and Spurs are the only two teams to maintain perfect records through multiple Finals series. As of July 2009, the Spurs rank third among active franchises for the highest winning percentage in NBA history; they have only missed the playoffs four times as an NBA franchise.\n",
            "The Toronto Raptors are a professional basketball team based in Toronto, Ontario. They are part of the Atlantic Division of the Eastern Conference in the National Basketball Association. The team was established in 1995, along with the Vancouver Grizzlies, as part of the NBA’s expansion into Canada. When the Grizzlies relocated to Memphis, Tennessee, to become the Memphis Grizzlies in 2001, the Raptors became the only Canadian team in the NBA. They originally played their home games at the SkyDome, before moving to the Air Canada Centre in 1999.\n",
            "The Utah Jazz are a professional basketball team based in Salt Lake City, Utah. They are currently a part of the Northwest Division of the Western Conference in the National Basketball Association. The franchise began in 1974 as the New Orleans Jazz in New Orleans, Louisiana, but the team moved to Utah in 1979 after just five seasons. The Jazz were one of the most unsuccessful teams in the league in their early years, and took 10 years before they made a playoff appearance. They would not miss the playoffs again until 2004. During the late 1980s, John Stockton and Karl Malone arose as the franchise players for the team, and formed one of the most famed point guard–power forward duos in NBA history. Led by coach Jerry Sloan, who took over for Frank Layden in 1988, they became one of the powerhouse teams of the 1990s, culminating in two NBA Finals appearances in 1997 and 1998, where they lost both times to the Chicago Bulls, led by Michael Jordan. Both Stockton and Malone moved on in 2003. After missing the playoffs for three consecutive seasons the Jazz returned to prominence under the on-court leadership of point guard Deron Williams. However, partway through the 2010–11 season, the Jazz began a restructuring after the retirement of Jerry Sloan and trade of Deron Williams. As of 2012, the Jazz are the only team in the major professional North American sports leagues located in the state of Utah.\n",
            "The Washington Wizards are a professional basketball franchise based in Washington, D.C. They are part of the Southeast Division of the Eastern Conference in the National Basketball Association. The team plays their home games at the Verizon Center, in the Chinatown neighborhood of Washington, D.C.\n",
    };

    private static int[]thumbnail = new int[]{R.drawable.img_atlanta_hawks, R.drawable.img_boston_celtics,
            R.drawable.img_brooklyn_nets, R.drawable.img_charlotte_bobcats, R.drawable.img_chicago_bulls,
            R.drawable.img_cleveland_cavaliers, R.drawable.img_dallas_mavericks,
            R.drawable.img_denver_nuggets, R.drawable.img_detroit_pistons, R.drawable.img_golden_state_warriors,
            R.drawable.img_houston_rockets, R.drawable.img_indiana_pacers, R.drawable.img_los_angeles_clippers,
            R.drawable.img_los_angeles_lakers, R.drawable.img_memphis_grizzlies, R.drawable.img_miami_heat,
            R.drawable.img_milwaukee_bucks, R.drawable.img_minnesota_timberwolves, R.drawable.img_new_orleans_hornets,
            R.drawable.img_new_york_knicks, R.drawable.img_oklahoma_city_thunder, R.drawable.img_orlando_magic,
            R.drawable.img_philadelphia_76ers, R.drawable.img_phoenix_suns, R.drawable.img_portland_trail_blazers,
            R.drawable.img_sacramento_kings, R.drawable.img_san_antonio_spurs, R.drawable.img_toronto_raptors,
            R.drawable.img_utah_jazz, R.drawable.img_washington_wizards
    };


    public static ArrayList<NbaModel> getListData(){
        NbaModel nbaModel = null;
        ArrayList<NbaModel> list = new ArrayList<>();
        for (int i = 0;i<title.length;i++){
            nbaModel = new NbaModel();
            nbaModel.setThumbnail(thumbnail[i]);
            nbaModel.setTitle(title[i]);
            nbaModel.setDetail(detail[i]);
            list.add(nbaModel);
        }
        return list;
    }
}
